name: "RedSock/Releaser"
description: "Creates Docker image and pushes it to Dockerhub or Private registry"

author: "RedSock"

branding:
  icon: "git-pull-request"
  color: "red"

inputs:
  REGISTRY_URL:
    description: "URL Name of private Docker registry to push to"
    default: "docker.io"
  REGISTRY_USER:
    description: "Registry user"
    required: true
  REGISTRY_PWD:
    description: "Registry tag"
    required: true
outputs:
  page_url:
    value:
    description: 'URL to deployed GitHub Pages'

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ github.ref }}
        fetch-depth: 0

    - name: Set up Docker BuildX
      uses: docker/setup-buildx-action@v3

    - name: Get Latest Tag
      uses: WyriHaximus/github-action-get-previous-tag@v1.4.0
      id: git_tag

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.REGISTRY_URL }}
        username: ${{ inputs.REGISTRY_USER }}
        password: ${{ inputs.REGISTRY_PWD }}

    - name: Build image to dockerhub
      shell: bash
      run: |
        IMAGE_NAME=${{ github.event.repository.name }}
        IMAGE_NAME=$(echo IMAGE_NAME | tr '[A-Z]' '[a-z]')
        
        IMAGE_ID=${{ inputs.REGISTRY_USER }}/$IMAGE_NAME
        IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
        
        VERSION=$(echo "${{ steps.git_tag.outputs.tag }}" | sed -e 's,.*/\(.*\),\1,')
        
        echo IMAGE_ID=$IMAGE_ID
        echo VERSION=$VERSION
        docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
        docker push $IMAGE_ID:$VERSION
        
        docker build \
        -t $IMAGE_NAME:$IMAGE_VERSION \
        -t $IMAGE_NAME:latest .
        
        docker push $IMAGE_NAME:$IMAGE_VERSION
        docker push $IMAGE_NAME:latest
